# Sample Jekyll Image Tag settings

name: A responsive Jekyll blog
pygments: true

image:
  source_path: "assets/images/_fullsize"
  output_path: "assets/images/generated"
  presets:
    # Proportional preset
    users:
      attr:
        class: "user-portrait"
        itemprop: "image"
      width: "350"
    # Scaled and cropped preset
    half:
      width: "400"
      height: "400"