# Sample Jekyll Image Tag settings

name: A Jekyll blog
pygments: true

img:
  source: assets/images/_fullsize
  output: generated
  presets:
    # Proportional preset
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    # Scaled and cropped preset
    half:
      width: 400
      height: 400